version: '3.8'
services:
  main:
    container_name: main
    image: node:20-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "if [ '${NODE_ENV:-development}' = 'production' ]; then npm install && npm run build && npm run start; else npm install && npm run dev; fi"
    networks:
      - basilisk_network
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS:-root}
      - MONGO_INITDB_DATABASE=${MONGO_DB:-basilisk}
    networks:
      - basilisk_network

networks:
  basilisk_network:
    name: basilisk_network
    driver: bridge

volumes:
  mongo_data:
    driver: local